[theme]
theme = "native"

[[block]]
block = "menu"
text = " Rotate "
[[block.items]]
display = " -&gt; Toggle &lt;-"
cmd = "exec swaymsg output eDP-1 transform $(swaymsg -t get_outputs | grep -q normal && echo 90 || echo normal)"

[[block]]
block = "menu"
text = " Power "
[[block.items]]
display = "-&gt; Shutdown &lt;-"
cmd = "poweroff"
confirm_msg = " Shutdown now? "
[[block.items]]
display = "-&gt; Reboot &lt;-"
cmd = "reboot"
confirm_msg = " Reboot now? "

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R') "

[[block]]
block = "keyboard_layout"
driver = "sway"
sway_kb_identifier = "1:1:AT_Translated_Set_2_keyboard"

[[block]]
block = "backlight"
format = " Screen $brightness "

[[block]]
block = "sound"
format = " Audio {$volume|muted} "

[[block]]
block = "cpu"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90

[[block]]
block = "memory"
format = " RAM $mem_used_percents "
format_alt = " SWP $swap_used_percents "

[[block]]
block = "net"
format = " $ssid $signal_strength "

[[block]]
block = "battery"
format = " Battery $percentage "
